// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace TpLib
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "tp_lib_net";





        /// <summary>
        ///  Project GNSS positions onto the nearest network segments.
        ///
        ///  # Safety
        ///  All pointers must reference valid UTF-8 byte slices of the indicated length.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tp_net_project_gnss", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer tp_net_project_gnss(byte* network_ptr, int network_len, byte* gnss_ptr, int gnss_len, ProjectionConfigFfi config);

        /// <summary>
        ///  Project GNSS positions onto a previously computed train path.
        ///
        ///  # Safety
        ///  All pointers must reference valid UTF-8 byte slices of the indicated length.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tp_net_project_onto_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer tp_net_project_onto_path(byte* network_ptr, int network_len, byte* gnss_ptr, int gnss_len, byte* train_path_ptr, int train_path_len, PathConfigFfi config);

        /// <summary>
        ///  Calculate a train path from GNSS positions and a railway network.
        ///
        ///  `prepared_detections_ptr` may be null (`prepared_detections_len == 0`).
        ///  When provided, the JSON must include an `anchors` array of [`ResolvedAnchor`].
        ///
        ///  # Safety
        ///  All non-null pointers must reference valid UTF-8 byte slices of the
        ///  indicated length.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tp_net_calculate_train_path", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer tp_net_calculate_train_path(byte* network_ptr, int network_len, byte* gnss_ptr, int gnss_len, byte* prepared_detections_ptr, int prepared_detections_len, PathConfigFfi config);

        /// <summary>
        ///  Validate, time-filter and resolve detections into [`ResolvedAnchor`]s for
        ///  path calculation.
        ///
        ///  `kind_is_linear == 0` ⇒ `Punctual`; non-zero ⇒ `Linear`.
        ///
        ///  # Safety
        ///  All pointers must reference valid UTF-8 byte slices of the indicated length.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tp_net_prepare_detections", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ByteBuffer tp_net_prepare_detections(byte* network_ptr, int network_len, byte* gnss_ptr, int gnss_len, byte* detections_geojson_ptr, int detections_geojson_len, byte kind_is_linear, double cutoff_distance_meters);

        /// <summary>
        ///  Free a [`ByteBuffer`] previously returned by any `tp_net_*` function.
        ///
        ///  # Safety
        ///  The buffer must have been produced by this library and not yet freed.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "tp_net_free_byte_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void tp_net_free_byte_buffer(ByteBuffer buf);


    }

    /// <summary>
    ///  Heap-allocated byte buffer owned by the Rust side; freed by the caller via
    ///  [`tp_net_free_byte_buffer`].
    ///
    ///  `len == cap` after allocation. A null `ptr` paired with `len == -1`
    ///  signals an FFI error (the C# layer raises a generic exception).
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ByteBuffer
    {
        public byte* ptr;
        public int len;
        public int cap;
    }

    /// <summary>
    ///  Flat mirror of `tp_lib_core::ProjectionConfig` for `#[repr(C)]` transport.
    ///
    ///  `max_search_radius_meters` is reserved for the public contract but is not
    ///  currently consumed by `tp-lib-core`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ProjectionConfigFfi
    {
        public double max_search_radius_meters;
        public double projection_distance_warning_threshold;
        public byte suppress_warnings;
    }

    /// <summary>
    ///  Flat mirror of `tp_lib_core::PathConfig` for `#[repr(C)]` transport.
    ///
    ///  `anchors` are not transmitted via this struct; they arrive on the
    ///  `PreparedDetections` JSON payload of `tp_net_calculate_train_path`.
    /// </summary>
    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PathConfigFfi
    {
        public double distance_scale;
        public double heading_scale;
        public double cutoff_distance;
        public double heading_cutoff;
        public double probability_threshold;
        public double resampling_distance;
        public byte has_resampling_distance;
        public ulong max_candidates;
        public byte path_only;
        public byte debug_mode;
        public double beta;
        public double edge_zone_distance;
        public double turn_scale;
        public double detection_cutoff_distance;
    }



}
